[33mWARNING:[0m underlay of /usr/bin/nvidia-smi required more than 50 (450) bind mounts
WARNING: You are using pip version 20.2.2; however, version 20.2.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
2020-09-29 15:50:41.307083: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
2020-09-29 15:50:41.307124: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING: You are using pip version 20.2.2; however, version 20.2.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
WARNING: You are using pip version 20.2.2; however, version 20.2.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
[I 15:50:55.530 NotebookApp] Serving notebooks from local directory: /home/users/industry/sp/wp_wong/Desktop
[I 15:50:55.530 NotebookApp] Jupyter Notebook 6.1.3 is running at:
[I 15:50:55.530 NotebookApp] http://gpu1720:8899/
[I 15:50:55.530 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 15:54:06.142 NotebookApp] 302 POST /login?next=%2Ftree%3F (192.168.153.3) 55.28ms
[I 15:54:28.932 NotebookApp] Kernel started: 503e6947-9c55-4536-b726-c76e8d85b8de, name: python3
2020-09-29 15:54:38.238615: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
2020-09-29 15:54:38.238648: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-29 15:54:43.761860: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-09-29 15:54:43.783812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:82:00.0 name: Tesla K40t computeCapability: 3.5
coreClock: 0.8755GHz coreCount: 15 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 268.58GiB/s
2020-09-29 15:54:43.783943: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
2020-09-29 15:54:43.784485: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
2020-09-29 15:54:43.784735: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
2020-09-29 15:54:43.784929: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
2020-09-29 15:54:43.785123: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
2020-09-29 15:54:43.785311: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs
2020-09-29 15:54:43.980198: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-09-29 15:54:43.980240: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-09-29 15:54:43.980662: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-29 15:54:43.996528: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2593915000 Hz
2020-09-29 15:54:43.998782: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x523a480 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-29 15:54:43.998814: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-29 15:54:44.003719: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-29 15:54:44.003742: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      
[I 15:56:28.888 NotebookApp] Saving file at /FirstTest.ipynb
[I 15:58:28.878 NotebookApp] Saving file at /FirstTest.ipynb
[I 15:59:59.100 NotebookApp] Starting buffering for 503e6947-9c55-4536-b726-c76e8d85b8de:7e8c1865b9994e9f851f9a34cfcee4cf
[C 16:02:07.187 NotebookApp] received signal 15, stopping
[I 16:02:07.190 NotebookApp] Shutting down 1 kernel
[I 16:02:08.393 NotebookApp] Kernel shutdown: 503e6947-9c55-4536-b726-c76e8d85b8de
[I 16:02:08.397 NotebookApp] Shutting down 0 terminals
[I 16:02:08.399 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
[E 16:02:08.399 NotebookApp] Exception in callback <bound method KernelRestarter.poll of <jupyter_client.ioloop.restarter.IOLoopKernelRestarter object at 0x2aaab57ae828>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/usr/local/lib/python3.6/dist-packages/jupyter_client/restarter.py", line 113, in poll
        self.kernel_manager.restart_kernel(now=True, newports=newports)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_client/manager.py", line 442, in restart_kernel
        self.shutdown_kernel(now=now, restart=True)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_client/manager.py", line 383, in shutdown_kernel
        self._kill_kernel()
      File "/usr/local/lib/python3.6/dist-packages/jupyter_client/manager.py", line 487, in _kill_kernel
        raise RuntimeError("Cannot kill kernel. No kernel is running!")
    RuntimeError: Cannot kill kernel. No kernel is running!
